name: Build Ghostty

on:
  pull_request:
  push:
    branches:
      - main
      - "22.04"
  workflow_dispatch:
    inputs:
      release_version:
        description: If empty, rest with build artifact. If nonempty, release that version.
        type: string
        required: false

permissions:
  contents: write

jobs:
  build-ghostty:
    name: Build Ghostty
    strategy:
      matrix:
        source_only: [true, false]
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Checkout ghostty-ubuntu
        uses: actions/checkout@v4

      - name: Build Ghostty
        run: |
          ARGS=""
          if [ "${{ matrix.source_only }}" = "true" ]; then
            ARGS="-S"
          fi
          echo "build-ghostty ARGS: $ARGS"
          ./build-ghostty.sh "$ARGS"
      
      - name: Upload Artifact
        if: inputs.release_version == ''
        uses: actions/upload-artifact@v4
        with:
          name: package-22.04-${{ matrix.source_only }}
          retention-days: 7
          path: |
            ghostty_*.*
        